#!/bin/bash
set -e

export PGPASSWORD="$DB_PASSWORD"

until psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c '\q' 2>/dev/null; do
  echo "Waiting"
  sleep 1
done

psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" <<EOSQL
DO
\$do\$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles WHERE rolname = '${NEW_USER}'
   ) THEN
      CREATE USER ${NEW_USER} WITH PASSWORD '${NEW_USER_PASSWORD}';
   END IF;
END
\$do\$;

GRANT CONNECT ON DATABASE ${DB_NAME} TO ${NEW_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${NEW_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${NEW_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${NEW_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${NEW_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${NEW_USER};
EOSQL