services:
  db:
    image: postgres:16
    container_name: order-api-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator:
    image: migrate/migrate:4
    container_name: order-api-migrator
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["-database", "${DATABASE_URL}",
              "-path", "/migrations",
              "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

volumes:
  data: